# Generated by Django 4.0.6 on 2022-07-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raid_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidrecord',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='종료시간'),
        ),
    ]
