<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-07-12 00:02
=======
# Generated by Django 4.0.6 on 2022-07-12 01:30
>>>>>>> 4a40f8d0182aa74a0adddb6455a555a0f2b6f8b8

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BossRaid',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=0, verbose_name='레벨')),
                ('level_clear_score', models.IntegerField(default=0, verbose_name='레벨 클리어점수')),
<<<<<<< HEAD
                ('time_limit', models.IntegerField(default=180, verbose_name='제한시간')),
=======

                ('time_limit', models.IntegerField(default=0, verbose_name='제한시간')),
>>>>>>> 4a40f8d0182aa74a0adddb6455a555a0f2b6f8b8
            ],
        ),
    ]
