# Generated by Django 4.0.6 on 2022-07-13 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BossRaid',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=0, verbose_name='레벨')),
                ('level_clear_score', models.IntegerField(default=0, verbose_name='레벨 클리어점수')),
                ('time_limit', models.IntegerField(default=0, verbose_name='제한시간')),
            ],
        ),
        migrations.CreateModel(
            name='RaidRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=0, verbose_name='레벨')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='획득점수')),
                ('enter_time', models.DateTimeField(auto_now_add=True, verbose_name='시작시간')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='종료시간')),
                ('level_clear_score', models.IntegerField(default=0, verbose_name='레벨 클리어점수')),
                ('time_limit', models.IntegerField(default=0, verbose_name='제한시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
    ]