# Generated by Django 4.0.6 on 2022-07-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BossRaid',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=0, verbose_name='레벨')),
                ('level_clear_score', models.IntegerField(default=0, verbose_name='레벨 클리어점수')),
                ('time_limit', models.IntegerField(default=180, verbose_name='제한시간')),
            ],
        ),
    ]
