# Generated by Django 4.0.6 on 2022-07-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss_raid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidrecord',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='획득점수'),
        ),
    ]
