# Generated by Django 4.0.6 on 2022-07-12 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boss_raid', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(verbose_name='획득점수')),
                ('enter_time', models.DateTimeField(auto_now_add=True, verbose_name='시작시간')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='종료시간')),
                ('boss_raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raid_record', to='boss_raid.bossraid', verbose_name='보스레이드')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
    ]
